// Production contract audit. Live prediction/service acceptance is separate and opt-in.
const test=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');
const base=process.env.TEST_BASE_URL||'http://localhost:5000';
async function request(route,body,token){const r=await fetch(base+route,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};}
let account;
test.before(async()=>{const email=crypto.randomUUID()+'@example.test';const r=await request('/api/auth/register',{email,name:'Fixture',password:'SecurePass123!',confirmPassword:'SecurePass123!'});assert.equal(r.status,201);account=(await request('/api/auth/login',{email,password:'SecurePass123!'})).data;});
test('health endpoint exposes dependency state without credentials',async()=>{const r=await request('/health');assert.equal(r.status,200);assert.equal(r.data.status,'online');assert.ok(r.data.services.database);assert.equal(JSON.stringify(r.data).includes('mongodb://'),false);});
test('readiness fails closed when isolated test database is offline',async()=>{const r=await request('/ready');assert.equal(r.status,503);assert.equal(r.data.ready,false);assert.ok(r.data.dependencies.authentication);});
test('AI routes require authentication',async()=>{assert.equal((await request('/api/ai/chat',{message:'Hello'})).status,401);assert.equal((await request('/api/agents/chat',{message:'Hello'})).status,401);});
test('authenticated AI reply has structured agent states and no fake confidence',async()=>{const r=await request('/api/ai/chat',{message:'When should I irrigate?',sessionId:'contract'},account.token);assert.equal(r.status,200);assert.equal(typeof r.data.response,'string');assert.ok(Array.isArray(r.data.agents));assert.equal(r.data.confidence,null);assert.ok(r.data.agents.some(a=>a.name==='Irrigation Agent'&&a.status==='MISSING_INPUT'));});
test('invalid coordinates reject',async()=>{assert.equal((await request('/api/location/reverse-geocode?lat=999&lon=999')).status,400);});
test('manual location remains supported',async()=>{const r=await request('/api/location/parse-manual',{location:'Warangal, Telangana'});assert.equal(r.status,200);assert.equal(r.data.formattedAddress,'Warangal, Telangana, India');});
test('weather requires location',async()=>{assert.equal((await request('/api/market/weather')).status,400);});
test('crop inference rejects incomplete inputs',async()=>{assert.equal((await request('/api/crop/recommend',{N:90})).status,400);});
test('missing model returns no invented crop or explanation',async()=>{const r=await request('/api/crop/recommend',{N:90,P:42,K:43,temperature:25,humidity:75,ph:6.5,rainfall:200});assert.equal(r.status,503);assert.equal(r.data.recommended_crop,undefined);assert.equal(r.data.shap_explanation,undefined);});
test('unconfigured yield and FL do not simulate success',async()=>{assert.equal((await request('/api/crop/yield',{crop:'Wheat'})).status,503);assert.equal((await request('/api/fl/status')).status,503);});
test('nutrient calculator requires explicit targets and source',async()=>{assert.equal((await request('/api/crop/fertilizer',{N:90,P:42,K:43,crop:'Wheat'})).status,400);const r=await request('/api/crop/fertilizer',{crop:'Fixture',areaAcres:1,nutrientTargets:{N:60,P:30,K:20},rateSource:'TEST FIXTURE'});assert.equal(r.status,200);assert.equal(r.data.data.mode,'GENERAL_PLAN');assert.equal(r.data.data.soilTest,null);});
test('filename cannot masquerade as disease image',async()=>{const r=await request('/api/disease/diagnose',{filename:'tomato_early_blight.png'});assert.equal(r.status,400);assert.equal(r.data.disease_name,undefined);});
test('bundled disease samples use an allowlist',async()=>{const valid=await fetch(base+'/api/disease/samples/tomato_early_blight');assert.equal(valid.status,200);assert.match(valid.headers.get('content-type')||'',/^image\/png/);assert.ok((await valid.arrayBuffer()).byteLength>0);const invalid=await fetch(base+'/api/disease/samples/..%2F..%2F.env');assert.equal(invalid.status,404);});
test('market forecast without stored data is explicitly unavailable',async()=>{const r=await request('/api/market-forecast/forecast?commodity=Tomato');assert.equal(r.status,200);assert.equal(r.data.status,'INSUFFICIENT_DATA');assert.deepEqual(r.data.forecast,[]);});
test('calendar BOM parsed and crop route opens',async()=>{const r=await request('/api/calendar/crops');assert.equal(r.status,200);assert.ok(r.data.crops.length>0);const c=await request('/api/calendar/'+encodeURIComponent(r.data.crops[0].key));assert.equal(c.status,200);assert.ok(c.data.months);});
test('profitability unauthorized and valid authenticated sensitivity',async()=>{const payload={cropName:'Fixture',landSizeAcres:1,expectedYieldQuintalsPerAcre:10,expectedPricePerQuintal:1000,customInputCosts:{seed:100,fertilizer:0,pesticides:0,irrigation:0,labor:0,machinery:0,transport:0,miscellaneous:0}};assert.equal((await request('/api/profitability/calculate',payload)).status,401);const r=await request('/api/profitability/sensitivity',payload,account.token);assert.equal(r.status,200);assert.equal(r.data.data.expected.estimatedGrossMargin,9900);});
test('satellite requires actual connected imagery',async()=>{const r=await request('/api/satellite/ndvi');assert.equal(r.status,503);assert.equal(r.data.grid,undefined);});
test('forgot password does not leak account membership or reset secret',async()=>{const r=await request('/api/auth/forgot-password',{email:crypto.randomUUID()+'@example.test'});assert.equal(r.status,200);assert.equal(r.data.resetToken,undefined);});
